[package]
name = "menu_genie"
version = "0.1.0"
edition = "2021"
authors = ["Dusan Djordjic"]
repository = "https://github.com/DusanDjordjic/MenuGenie"
description = "Multi-level terminal menu library."
keywords = ["terminal", "menu"]

[lib]
name = "menu_genie"
path = "src/lib.rs"

[dependencies]
